# Generated by Django 5.0.2 on 2024-03-18 10:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post_problem')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apply_request',
            },
        ),
        migrations.CreateModel(
            name='Worker_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('work_description', models.TextField()),
                ('worker_image', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='disable', max_length=20)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.category')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.city')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.sub_category')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_profile',
            },
        ),
    ]
